title: SoloScripted - AI-Powered Game Development
email: info@soloscripted.com
description: >-
  SoloScripted: Crafting innovative AI-powered games for mobile and web.
  Explore unique gaming experiences.
url: "https://soloscripted.com"
keywords: "AI game development, solo game developer, indie games, mobile games, web games, Sudokode, AI-powered games, game development, innovative games"
baseurl: ""

github_username: soloscripted
twitter_username: soloscrptd
linkedin_company: soloscripted

plugins:
  - jekyll-sitemap
