# This GitHub Actions workflow automates the process of creating a new release
# whenever a new version tag (e.g., v1.0.0, v1.2.3) is pushed to the repository.

name: Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on push events to tags that match the pattern v*.*.*

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is required for the action to create a release.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true
          working-directory: './docs'

      - name: Build site with Makefile
        run: make build
    
      - name: Archive site artifacts
        run: zip -r site-artifacts.zip ./docs/_site

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "See the commit history for details."
          files: site-artifacts.zip
          generate_release_notes: true
